Change Kennytv's reason + add My Project
kennytv/list-of-shame pull request #102
Opened 2024-06-24 02:07 UTC by Outfit8TSB

Proof:
🔭 I mainly work on Paper, ViaVersion <-- , and Hangar. - from kennytv/readme.md
![Screenshot_20240624-104413](https://github.com/kennytv/list-of-shame/assets/167604853/9d9250ee-eab1-4eaa-a8fd-3f42aa9b39a5)
You Work on ViaVersion means you working on one of dank project called viaversion.
to that continously let evil to live.
3 of My Projects are using GeyserMC Because i only have is Bedrock Edition. i should've created bukkit plugins instead.
(note: i forgot to add spottedleaf for adding kennytv,indirectly merging one of retrooper's pr. so this pull request is draft until spottedleaf is added.)
if this pr won't merge, add me in this list of shame instead, because,
i mashed 2 server softwares, which is PlazmaMC and LeavesMC, in one server software to boycott International Organization.
i also created pull request that dosen't make any sense to turn into a dictator of server software.(eventhough one of responder how to port pufferfish properly without turning my project into dank project, but it turns out it transformed into dank project)
i am also turned into dictator of server software by creating MultiNet(Minestom) and NogyangSpigot(NMS)

2024-07-11 02:18 UTC, Badbird5907 commented
huh wheres my free tacos

2024-07-11 02:23 UTC, Badbird5907 requested changes

2024-07-11 02:23 UTC, Badbird5907 commented on README.md
> +    * [MagmaMC](https://github.com/MagmaFoundation/Magma) - Brake EssentialsX Code([See The Warning](https://essentialsx.net/downloads.html)) and also [Abused log4j bug](https://pixelmonmod.com/viewt
I need to change the brakes on my bike too

2024-07-11 08:08 UTC, Outfit8TSB commented
@Badbird5907 sorry, this is pull request not tacohouse

2024-07-11 12:40 UTC, Badbird5907 commented
But I was promised free tacos >:(

2024-07-15 07:35 UTC, Outfit8TSB commented
ugh, badbird, NO TACOS HERE!

2024-07-16 12:45 UTC, Outfit8TSB commented
kenny merge this or close it and lock it badbird5907 is annoying me

2024-07-16 12:46 UTC, Outfit8TSB commented
ok that's it i am pushing more

2024-08-06 06:31 UTC, closed without merging

2024-08-06 06:31 UTC, Outfit8TSB commented
you know what this pull is worthless because of badbird5907 asking me free tacos
add me and him later.

2024-08-08 00:59 UTC, Badbird5907 commented
womp womp