Add skript
KennyTV/list-of-shame pull request #19
Opened 2021-01-09 21:14 UTC by KoxSosen

2021-01-09 21:43 UTC, mbax commented
Unnecessary comma.

2021-01-09 22:12 UTC, KennyTV requested changes

2021-01-09 22:12 UTC, KennyTV commented on README.md
> +* [Skript](https://github.com/SkriptLang/Skript) - "Programming language, that allows server owners to modify their servers without learning Java" - Widely used preformance killer by people, who beli
```suggestion
* [Skript](https://github.com/SkriptLang/Skript) - "Programming language that allows server owners to modify their servers without learning Java" - Widely used preformance killer by people, who believe that putting 2 phrases next to each other in Skript makes them a developer. Not to mention the thousands of [forks](https://skunity.com/), claimimg to "improve preformance".
```

2021-01-12 15:22 UTC, Andre601 commented on README.md
> +* [Skript](https://github.com/SkriptLang/Skript) - "Programming language, that allows server owners to modify their servers without learning Java" - Widely used preformance killer by people, who beli
I personally would go with `Wanna-be Programming language` as I can't even see skript as actual programming and more as scripting itself.
Pretty sure other Java devs would agree on this.

2021-01-12 16:40 UTC, E404NNF commented
i think you should mention minehut somewhere?

2021-01-13 07:43 UTC, PikaMug commented
Skript is a strange animal. The developers are careful not to bill it as a programming language. It's essentially a kid's learning tool and one might imagine the original creator realized that in naming the plugin so aptly. It currently does not support "**the evil**" (1.8) and although most everything written with it is garbage, it does have it's own, separate trash-heap of a category on SpigotMC so we don't have to smell the abhorrent stench. In conclusion: very stinky, but **not** shameful.

2021-01-13 07:50 UTC, closed without merging